app/Http/routes.php
<?php

Route::auth();

//USER
Route::resource('/', 'User\WelcomeController@index');
Route::post('/pengaduan/store', 'User\WelcomeController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/moto', 'User\ProfilController@moto');
Route::resource('/profil/tujuan', 'User\ProfilController@tujuan');
Route::resource('/profil/sasaran', 'User\ProfilController@sasaran');
Route::resource('/profil/struktur', 'User\ProfilController@struktur');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/layanan/ukl', 'User\LayananController@ukl');
Route::resource('/layanan/lb3', 'User\LayananController@lb3');
Route::resource('/layanan/iplc', 'User\LayananController@iplc');
Route::resource('/layanan/sedotwc', 'User\LayananController@sedotwc');
Route::resource('/layanan/pengelolaansampah', 'User\LayananController@sampah');

Route::resource('/program', 'User\ProgramController@program');
Route::resource('/kebijakan', 'User\ProgramController@kebijakan');

Route::resource('/regulasi/undang', 'User\RegulasiController@undang');
Route::resource('/regulasi/peraturandaerah', 'User\RegulasiController@daerah');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::get('/admin/berita/publish/{id}', 'Admin\BeritaController@publish');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/video', 'Admin\VideoController');
Route::resource('/admin/gallery', 'Admin\AlbumController');
Route::resource('/admin/foto', 'Admin\GalleryController');

Route::resource('/admin/regulasi', 'Admin\RegulasiController');
Route::resource('/admin/profil', 'Admin\ProfilController');
Route::resource('/admin/layanan', 'Admin\LayananController');
Route::resource('/admin/programkebijakan', 'Admin\ProgramController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');
Route::resource('/admin/komentar', 'Admin\KomentarController');

resources/views/admin/info/edit_info.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Info
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah Info</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($info, ['route' => ['admin.info.update', $info],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_info', ['model' => $info])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/info/info.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Informasi
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <!-- Akun -->
            <div class="col-md-12">
                <div class="box box-primary">

                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.info.store', 'class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_info')
                        {!! Form::close() !!}
                    </div>
                </div>
                <div class="box box-primary">

                    <div class="box-body" style="overflow-x:auto;">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="150px">Judul</th>
                                <th>Isi</th>
                                <th colspan="2">Aksi</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($info as $item)
                                <tr>
                                    <td><b>{{ $item->meta_key }}</b></td>
                                    <td>{!! str_limit($item->meta_value, 100) !!}</td>
                                    <td align="center">
                                        <a href="{{ route('admin.info.show', $item->id) }}" class="btn btn-success">Lihat</a>
                                    </td>
                                    <td align="center">
                                        <a href="{{ route('admin.info.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/info/show_info.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Info
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{$info->meta_key}}</h3>
                    </div>
                    <div class="box-body">
                        {!! $info->meta_value !!}
                    </div>
                    <div class="box-body" align="right">
                        <a href="{{ route('admin.info.index') }}" class="btn btn-success">Kembali</a>
                        <a href="{{ route('admin.info.edit', $info->id) }}" class="btn btn-primary">Ubah</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection