app/Http/routes.php
<?php

Route::auth();

//USER
Route::resource('/', 'User\WelcomeController@index');
Route::post('/pengaduan/store', 'User\WelcomeController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/moto', 'User\ProfilController@moto');
Route::resource('/profil/tujuan', 'User\ProfilController@tujuan');
Route::resource('/profil/sasaran', 'User\ProfilController@sasaran');
Route::resource('/profil/struktur', 'User\ProfilController@struktur');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/layanan/ukl', 'User\LayananController@ukl');
Route::resource('/layanan/lb3', 'User\LayananController@lb3');
Route::resource('/layanan/iplc', 'User\LayananController@iplc');
Route::resource('/layanan/sedotwc', 'User\LayananController@sedotwc');
Route::resource('/layanan/pengelolaansampah', 'User\LayananController@sampah');

Route::resource('/program', 'User\ProgramController@program');
Route::resource('/kebijakan', 'User\ProgramController@kebijakan');

Route::resource('/regulasi/undang', 'User\RegulasiController@undang');
Route::resource('/regulasi/peraturandaerah', 'User\RegulasiController@daerah');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::get('/admin/berita/publish/{id}', 'Admin\BeritaController@publish');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/video', 'Admin\VideoController');
Route::resource('/admin/gallery', 'Admin\AlbumController');
Route::resource('/admin/foto', 'Admin\GalleryController');

Route::resource('/admin/regulasi', 'Admin\RegulasiController');
Route::resource('/admin/profil', 'Admin\ProfilController');
Route::resource('/admin/layanan', 'Admin\LayananController');
Route::resource('/admin/programkebijakan', 'Admin\ProgramController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');
Route::resource('/admin/komentar', 'Admin\KomentarController');

resources/views/admin/beranda.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">

                <div align="center"><br><br>
                    <img src="../itlabil/images/default/logo-pesawaran.png" width="200" alt="logo">
                </div>
                <div align="center">
                    <p align="center">
                        <br><br>
                        <font size="4">PEMERINTAHAN KABUPATEN PESAWARAN</font><br>
                        <font size="6">DINAS LINGKUNGAN HIDUP</font><br>
                        {{$kontak->alamat}}
                    </p>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/pengaturan.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Pengaturan
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <!-- Akun -->
            <div class="col-md-6">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Akun Admin</h3>
                    </div>

                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td align="center">Email</td>
                                <td align="center">Password</td>
                                <td colspan="2" align="center">Aksi</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($user as $item)
                                <tr>
                                    <td>{{ $item->email }}</td>
                                    <td align="center">*****</td>
                                    <td align="center">
                                        <a href="{{ route('admin.pengaturan.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Kontak -->
            <div class="col-md-6">

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Kontak</h3>
                    </div>

                    <div class="box-body">
                        <table class="table table-bordered">
                            <tr>
                                <th>Telp</th>
                                <td>{{ $kontak->telp }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ $kontak->email }}</td>
                            </tr>
                            <tr>
                                <th>Instagram</th>
                                <td>{{ $kontak->instagram }}</td>
                            </tr>
                            <tr>
                                <th>Facebook</th>
                                <td>{{ $kontak->facebook }}</td>
                            </tr>
                            <tr>
                                <th>Twitter</th>
                                <td>{{ $kontak->twitter }}</td>
                            </tr>
                            <tr>
                                <th>Alamat</th>
                                <td>{{ $kontak->alamat }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" align="right">
                                    <a href="{{ route('admin.pengaturan.kontak.edit', $kontak->id) }}" class="btn btn-primary">Ubah</a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection