app/Http/routes.php
<?php

Route::auth();

//USER
Route::resource('/', 'User\WelcomeController@index');
Route::post('/pengaduan/store', 'User\WelcomeController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/moto', 'User\ProfilController@moto');
Route::resource('/profil/tujuan', 'User\ProfilController@tujuan');
Route::resource('/profil/sasaran', 'User\ProfilController@sasaran');
Route::resource('/profil/struktur', 'User\ProfilController@struktur');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/layanan/ukl', 'User\LayananController@ukl');
Route::resource('/layanan/lb3', 'User\LayananController@lb3');
Route::resource('/layanan/iplc', 'User\LayananController@iplc');
Route::resource('/layanan/sedotwc', 'User\LayananController@sedotwc');
Route::resource('/layanan/pengelolaansampah', 'User\LayananController@sampah');

Route::resource('/program', 'User\ProgramController@program');
Route::resource('/kebijakan', 'User\ProgramController@kebijakan');

Route::resource('/regulasi/undang', 'User\RegulasiController@undang');
Route::resource('/regulasi/peraturandaerah', 'User\RegulasiController@daerah');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::get('/admin/berita/publish/{id}', 'Admin\BeritaController@publish');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/video', 'Admin\VideoController');
Route::resource('/admin/gallery', 'Admin\AlbumController');
Route::resource('/admin/foto', 'Admin\GalleryController');

Route::resource('/admin/regulasi', 'Admin\RegulasiController');
Route::resource('/admin/profil', 'Admin\ProfilController');
Route::resource('/admin/layanan', 'Admin\LayananController');
Route::resource('/admin/programkebijakan', 'Admin\ProgramController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');
Route::resource('/admin/komentar', 'Admin\KomentarController');

app/Http/Controllers/Admin/AlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\AlbumFoto;
use App\Gallery;

class AlbumController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(Request $request)
    {
        $album = AlbumFoto::orderBy('id','DESC')->paginate(8);

        return view('admin.album.album', compact('album'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        // SIMPAN DATA SISWA META
        $album = $request->only('album');

        AlbumFoto::create($album);

        $notification = array(
            'message' => 'Album Baru berhasil dibuat.',
            'alert-type' => 'succes'
        );

        return redirect()->route('admin.gallery.index')->with($notification);
    }

    public function show($id)
    {
        $album = AlbumFoto::findOrFail($id);
        $foto = Gallery::where('album_id',$album->id)->orderBy('id','DESC')->paginate(8);

        return view('admin.album.show_album', compact('album','foto'));
    }


    public function edit($id)
    {
        $album = AlbumFoto::findOrFail($id);
        return view('admin.album.edit_album', compact('album'));
    }

    public function update(Request $request, $id)
    {
        $album = AlbumFoto::findOrFail($id);

        $dataalbum = $request->all();
        $album->update($dataalbum);

        $notification = array(
            'message' => 'Album berhasil diubah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.gallery.index')->with($notification);
    }

    public function destroy($id)
    {
        $album = AlbumFoto::findOrFail($id);

        $hapus = Gallery::where('album_id',$album->id)->get()->all();
        foreach ($hapus as $item) { 
            $this->deletePhoto($item->photo);
            Gallery::find($item->id)->delete();
        }

        $notification = array(
            'message' => 'Album '.$album->album.' berhasil dihapus.',
            'alert-type' => 'error'
        );

        AlbumFoto::find($id)->delete();

        return redirect()->route('admin.gallery.index')->with($notification);
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/images/gallery/'.$filename;
      return File::delete($path);
    }
}

resources/views/admin/album/album.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Album
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Album</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.gallery.store', 'class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_album')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="col-md-12">
                    @foreach($album as $item)
                        <div class="col-md-3">
                            <center>
                                @php($img='')
                                @foreach($item->gallery as $foto)
                                    @php($img = $foto->photo)
                                @endforeach
                                <a href="{{ route('admin.gallery.show', $item->id) }}">
                                    @if($img==='')
                                        <img src="../itlabil/admin/dist/img/images.png" alt="{{ $item->photo }}" class="img-thumbnail"><br>
                                    @else
                                        <img src="../itlabil/images/gallery/{{ $img }}" alt="{{ $item->photo }}" class="img-thumbnail" style="max-height:210px;"><br>
                                    @endif
                                </a>
                                
                                <h4>{{ $item->album }}</h3>
                                <!-- <div class="col-md-12" style="margin-top:5px;">
                                    <div class="col-md-4">
                                        <a href="{{ route('admin.gallery.show', $item->id) }}" class="btn btn-primary">Lihat</a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="{{ route('admin.gallery.edit', $item->id) }}" class="btn btn-success">Edit</a>
                                    </div>
                                    <div class="col-md-4">
                                        {!! Form::model($item, ['route' => ['admin.gallery.destroy', $item], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                                            {!! Form::submit('Hapus', ['class'=>'btn btn-danger js-submit-confirm']) !!}
                                        {!! Form::close()!!}
                                    </div>
                                </div> -->
                                
                                
                            </center><br><br>
                        </div>
                    @endforeach
                </div>
                <div class="col-md-12" align="center">
                    {{ $album->appends(compact('page'))->links() }}
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/album/edit_album.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Album
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Album</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($album, ['route' => ['admin.gallery.update', $album],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_album', ['model' => $album])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/album/show_album.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Album : {{$album->album}}
        </h1>
    </section>

    <div class="row" style="padding-top:10px;">
        <div class="col-md-12">
            <div class="col-md-2">
                {!! Form::model($album->id, ['route' => ['admin.gallery.destroy', $album->id], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                    {!! Form::submit('Hapus Album', ['class'=>'btn btn-danger js-submit-confirm']) !!}
                {!! Form::close()!!}
            </div>
            <div class="col-md-2">
                <a href="{{ route('admin.gallery.edit', $album->id) }}" class="btn btn-success">Edit Album</a>
            </div>
            <div class="col-md-8"></div>
        </div>
    </div>
        
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Gambar</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.foto.store', 'class'=>'form-horizontal','files'=>true,'enctype'=>'multipart/form-data'])!!}
                            @include('form._admin_gallery')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="col-md-12">
                    @foreach($foto as $item)
                        <div class="col-md-3">
                            <center>
                                <img src="../../itlabil/images/gallery/{{ $item->photo }}" alt="{{ $item->photo }}" class="img-thumbnail">
                                <div style="margin-top:5px;">
                                    {!! Form::model($item, ['route' => ['admin.foto.destroy', $item], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                                        {!! Form::submit('Hapus', ['class'=>'btn btn-danger js-submit-confirm']) !!}
                                    {!! Form::close()!!}
                                </div>
                                
                            </center><br><br>
                        </div>
                    @endforeach
                </div>
                <div class="col-md-12" align="center">
                    {{ $foto->appends(compact('page'))->links() }}
                </div>
            </div>
        </div>
    </section>
@endsection