app/Http/routes.php
<?php

Route::auth();

//USER
Route::resource('/', 'User\WelcomeController@index');
Route::post('/pengaduan/store', 'User\WelcomeController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/moto', 'User\ProfilController@moto');
Route::resource('/profil/tujuan', 'User\ProfilController@tujuan');
Route::resource('/profil/sasaran', 'User\ProfilController@sasaran');
Route::resource('/profil/struktur', 'User\ProfilController@struktur');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/layanan/ukl', 'User\LayananController@ukl');
Route::resource('/layanan/lb3', 'User\LayananController@lb3');
Route::resource('/layanan/iplc', 'User\LayananController@iplc');
Route::resource('/layanan/sedotwc', 'User\LayananController@sedotwc');
Route::resource('/layanan/pengelolaansampah', 'User\LayananController@sampah');

Route::resource('/program', 'User\ProgramController@program');
Route::resource('/kebijakan', 'User\ProgramController@kebijakan');

Route::resource('/regulasi/undang', 'User\RegulasiController@undang');
Route::resource('/regulasi/peraturandaerah', 'User\RegulasiController@daerah');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::get('/admin/berita/publish/{id}', 'Admin\BeritaController@publish');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/video', 'Admin\VideoController');
Route::resource('/admin/gallery', 'Admin\AlbumController');
Route::resource('/admin/foto', 'Admin\GalleryController');

Route::resource('/admin/regulasi', 'Admin\RegulasiController');
Route::resource('/admin/profil', 'Admin\ProfilController');
Route::resource('/admin/layanan', 'Admin\LayananController');
Route::resource('/admin/programkebijakan', 'Admin\ProgramController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');
Route::resource('/admin/komentar', 'Admin\KomentarController');

app/Regulasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Regulasi extends Model
{
    //
}

app/Http/Controllers/Admin/RegulasiController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Meta;

class RegulasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $no=1;
        $regulasi = Meta::where('meta_key','LIKE', '%Regulasi%')
                    ->get()->all();

        return view('admin.regulasi.regulasi', compact('regulasi','no'));
    }
    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        $regulasi = Meta::findOrFail($id);

        return view('admin.regulasi.show_regulasi', compact('regulasi'));
    }

    public function edit($id)
    {
        $regulasi = Meta::findOrFail($id);
        return view('admin.regulasi.edit_regulasi', compact('regulasi'));
    }

    public function update(Request $request, $id)
    {
        $regulasi = Meta::findOrFail($id);

        if ($request->hasFile('meta_value')) {
            $this->deletePhoto($regulasi->photo);
            $dataregulasi['meta_value'] = $this->savePhoto($request->file('meta_value'));
        }

        $regulasi->update($dataregulasi);

        $notification = array(
            'message' => 'Regulasi berhasil diubah.',
            'alert-type' => 'info'
        );
        return redirect()->route('admin.regulasi.index')->with($notification);
    }

    public function destroy($id)
    {
        //
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'itlabil/file';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/file/'.$filename;
      return File::delete($path);
    }
}

app/Http/Controllers/User/RegulasiController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Kontak;
use App\Meta;
class RegulasiController extends Controller
{

    public function undang()
    {
        $kontak = Kontak::where('id',1)->get()->first();
        $regulasi = Meta::where('meta_key','Regulasi - Undang-undang')->get()->all();
        return view('user.regulasi.undang',compact('kontak','regulasi'));
    }

    public function daerah()
    {
        $kontak = Kontak::where('id',1)->get()->first();
        $regulasi = Meta::where('meta_key','Regulasi - Peraturan Daerah')->get()->all();
        return view('user.regulasi.daerah',compact('kontak','regulasi'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/regulasi/edit_regulasi.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Regulasi
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah {{$regulasi->meta_key}}</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($regulasi, ['route' => ['admin.regulasi.update', $regulasi],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_regulasi', ['model' => $regulasi])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/regulasi/regulasi.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Regulasi
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Regulasi</h3>
                    </div>
                    <div class="box-body" style="overflow-x:auto;">

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td>No</td>
                                <td>Regulasi</td>
                                <td>Isi</td>
                                <td>Action</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($regulasi as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->meta_key }}</td>
                                    <td>
                                        <a href="{{ route('admin.regulasi.show', $item->id) }}" class="btn btn-primary">Lihat</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.regulasi.edit', $item->id) }}" class="btn btn-success">Ubah</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/regulasi/show_regulasi.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Regulasi
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ $regulasi->meta_key }}</h3>
                    </div>
                    <div class="box-body">
                        <object style="width: 100%; height: 500px;" type="application/pdf" data="/itlabil/file/{{$regulasi->meta_value}}?#zoom=85&scrollbar=0&toolbar=0&navpanes=0">
                            <p>File PDF tidak ditemukan.</p>
                        </object>
                    </div>
                    <div class="box-body" align="right">
                        <a href="{{ url('admin/regulasi') }}" class="btn btn-primary">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection